[colors]
background = #FFFFFF
foreground = #2D2D2D
primary = #444444

[bar/exemple]
width = 30%
height = 28
offset-x = 35%
offset-y = 12
radius = 14

background = ${colors.background}
foreground = ${colors.foreground}

border-size = 2
border-color = #DDDDDD

padding = 2
module-margin = 1
fixed-center = true

; --- IMPORTANT: Assure-toi d'avoir cette police installée ---
font-0 = "JetBrainsMono Nerd Font:size=10;2"

modules-center = xworkspaces date

[bar/top]
; On le détache pour qu'il flotte
override-redirect = true
fixed-center = true

; Largeur adaptée pour "Akira" + Icônes
width = 15%
height = 28
offset-x = 84%
offset-y = 12
radius = 14

background = #FFFFFF
foreground = #1A1B26

padding-left = 2
padding-right = 2
module-margin = 1

font-0 = "JetBrainsMono Nerd Font:size=10;3"

modules-center = network battery

[module/network]
type = internal/network
; --- IMPORTANT : Change wlan0 par le nom que tu vois avec 'ip link' ---
interface = wlan0
label-connected = "   %essid% "
label-disconnected = " 󰖪 "

[module/battery]
type = internal/battery
full-at = 99
; --- Souvent BAT0 ou BAT1 sur les laptops ---
battery = BAT0
adapter = AC
label-charging = " 󰂄 %percentage%% "
label-discharging = " 󰁹 %percentage%% "


[module/xworkspaces]
type = internal/xworkspaces
label-active = %name%
label-active-background = #E0E0E0
label-active-underline = #2D2D2D
label-active-padding = 1
label-occupied = %name%
label-occupied-padding = 1

[module/date]
type = internal/date
interval = 1
date = %H:%M
label = %date%
